name: MSBuild-v9

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: hid/vhidmini2/driver/kmdf/vhidmini2.vcxproj
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore NuGet Packages
      working-directory: hid/vhidmini2/driver/kmdf
      run: nuget restore

    - name: Build Solution
      working-directory: hid/vhidmini2/driver/kmdf
      run: |
        msbuild vhidmini2.vcxproj `
        /p:Configuration=$env:BUILD_CONFIGURATION `
        /p:Platform=Win32 `
        /p:OutputPath=./$env:BUILD_CONFIGURATION/

    - name: Verify Build Output
      working-directory: hid/vhidmini2/driver/kmdf
      run: dir $env:BUILD_CONFIGURATION

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: driver-binaries
        path: hid/vhidmini2/driver/kmdf/${{ env.BUILD_CONFIGURATION }}
