name: MSBuild-v5
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: hid/vhidmini2/driver/kmdf/vhidmini2.vcxproj
  BUILD_CONFIGURATION: Release
  OUTPUT_DIR: hid/vhidmini2/driver/kmdf/${{ env.BUILD_CONFIGURATION }}

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # 如果项目包含submodule需要添加这个参数
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet Packages
      working-directory: hid/vhidmini2/driver/kmdf
      run: nuget restore

    - name: Build Solution
      working-directory: hid/vhidmini2/driver/kmdf
      run: msbuild vhidmini2.vcxproj /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=Win32 /p:OutputPath=./${{ env.BUILD_CONFIGURATION }}/

    - name: Verify Build Output
      working-directory: hid/vhidmini2/driver/kmdf
      run: dir ${{ env.BUILD_CONFIGURATION }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: driver-binaries
        path: ${{ env.OUTPUT_DIR }}
